### PR TITLE
Add a launch.json vscode configuration for debug

### PR DESCRIPTION
**Pull request by tahini**
This file allows to run/debug trRouting from vscode.

### CODE REVIEW

**Comment by greenscientist** [comment]
This seems fine. Would there be any conflict with people vscode own configuration ??

**Comment by tahini** [comment]
There might indeed be conflicts if some people already have this file. They can probably easily be fixed. What I don't like is that even though it is in the .gitignore, changes to the file will be tracked though it will say

```
The following paths are ignored by one of your .gitignore files:
.vscode
Use -f if you really want to add them.
```

Should I rather rename it to launch.json.example?

**Comment by tahini** [comment]
A year and a half later, launch.json.example is here...

**Review by greenscientist — CHANGES_REQUESTED** [review]
Can you update the commit message to explain that it,s an example that people need to copy??

**Review by greenscientist — APPROVED** [review]

**Pull request merged**
