### PR TITLE
Rename the Parameters class to ServerParameters

### PR DESCRIPTION
**Pull request by tahini**
This will allow to eventually have another class for RouteParameters
where the part of the parameters that are specific for a single route query
will be moved.

Note that the ServerParameters class still contains a lot of non-server
parameters.

### CODE REVIEW

**Review by greenscientist — COMMENTED** [review]
I'm not sure that Server is an appropropriate name. CalculationParam ? InstanceParam ? 
There's a few thing yes about a deamon instance, but many other things. Thoughts?

**Comment by tahini** [comment]
> I'm not sure that Server is an appropropriate name. CalculationParam ? InstanceParam ?

Maybe InstanceParam, but indeed there's currently more Calculation parameters than instance params in this class, but since I was thinking to make a refactoring to extract the calculation params, the CalculationParam would be a new class in that later PR. But technically, I could also extract the Instance Parameters from the Calculation parameters, but it's just how you see it :p 

Maybe it's too early to rename this class then...

**Comment by greenscientist** [comment]
> 
> Maybe it's too early to rename this class then...

Maybe easier to keep this one, and chip pieces of it and then name those small chunk

**Comment by greenscientist** [comment]
But in the current context, since the deamon is everything. Saying it's a ServerParam is also true. I'll accept the change and let you decide if you prefer to abandon the diff or keep it

**Review by kaligrafy — APPROVED** [review]

**Comment by tahini** [comment]
I'll abandon, this class will be either removed or simply renamed when only one type of params remain in it.

**Pull request closed without merging**
