### PR TITLE
v2: Update the `route` json response to match API

### PR DESCRIPTION
**Pull request by tahini**
The API now has a status/query/result structure. The `route` endpoint is updated to match this API.

### CODE REVIEW

**Comment by tahini** [comment]
@kaligrafy Can you run the `make check` of this PR on your mac and post the failing csa_test.log file, I don't know why it fails...

**Comment by kaligrafy** [comment]
[csa_test.log](https://github.com/chairemobilite/trRouting/files/10231261/csa_test.log)

**Comment by tahini** [comment]
Thank you! size of 20? Sounds like memory pollution...

**Review by greenscientist — APPROVED** [review]
looks ok

**Pull request merged**
