### PR TITLE
Change simple-web to not use deprecated boost const_buffers_1

### PR DESCRIPTION
**Pull request by greenscientist**

### CODE REVIEW

**Comment by greenscientist** [comment]
Closes #301

**Review by tahini — COMMENTED** [review]
ok... and this Iterator is exactly equivalent and the same as previously? There is no other change required anywhere?

**Comment by greenscientist** [comment]
Seems to work...  
I've done Claude's suggestion, it's the only changes to make it compile. 

I've tested in transition, accessbility map and route calculations works . 

Guessing that with this change the right iterator types is picked up. I've sent the changes upstream, wondering if it will be picked as is.

**Review by tahini — COMMENTED** [review]
Which upstream? can you link to that PR to see what the upstream says? And fi there is an upstream, why do we have it here too?

Also, you change `client_http.hpp`, do you need to change `client_https.hpp` too? Or they are totally different files?

**Comment by greenscientist** [comment]
Upstream PR: https://gitlab.com/eidheim/Simple-Web-Server/-/merge_requests/279

We do it here since for that project it's customary to copy the simple file into the project. We also have some local modifications I think. 

We don't need to change client_https.hpp, it uses the content of client_http.hpp

**Review by tahini — APPROVED** [review]
I you say so!

**Pull request merged**
